import Head from "next/head";
import axios from "configs/axios";

export default function Home(props) {
  console.log(props);
  return (
    <div className="container mx-auto mt-4">
      <Head>
        <title>Kelas Micro</title>
        <meta name="description" content="Generated by Kelas Micro" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Halaman utama
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </main>
    </div>
  );
}

Home.getInitialProps = async () => {
  try {
    const data = await axios.get("/users");
    return { data };
  } catch (error) {
    return error;
  }
};
