import Head from "next/head";

export default function Home() {
  return (
    <div className="container mx-auto mt-4">
      <Head>
        <title>Kelas Micro</title>
        <meta name="description" content="Generated by Kelas Micro" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Halaman utama
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </main>
    </div>
  );
}
